// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
<<<<<<< HEAD
    apiKey: 'AIzaSyC4ypTFBh5GdcVKh11yFfWo7kZph5jvAjM',
    appId: '1:980675712346:android:398821cce9f00e4e008f63',
    messagingSenderId: '980675712346',
    projectId: 'bg-remover-871f9',
    storageBucket: 'bg-remover-871f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOwMGucgx6oTiaQhfaeD1VFtlVXAIrtH8',
    appId: '1:980675712346:ios:d142d62862f00224008f63',
    messagingSenderId: '980675712346',
    projectId: 'bg-remover-871f9',
    storageBucket: 'bg-remover-871f9.appspot.com',
    iosBundleId: 'com.uni.bgremove',
=======
    apiKey: 'AIzaSyDxc6Gulo0XaboccIe4xAzHJ-YErXYDb3U',
    appId: '1:667100006438:android:25ae2ea228c3118859bee7',
    messagingSenderId: '667100006438',
    projectId: 'background-remover-de307',
    storageBucket: 'background-remover-de307.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Tws0_wmtqEEG3MIFiblswIg3zWlfjRY',
    appId: '1:667100006438:ios:5589cf624b18c43b59bee7',
    messagingSenderId: '667100006438',
    projectId: 'background-remover-de307',
    storageBucket: 'background-remover-de307.appspot.com',
    iosBundleId: 'com.hk.smartRemove',
>>>>>>> 152f9fa8741191defaaf16dd3adbaf2eb1412137
  );
}
